CREATE TABLE IF NOT EXISTS plan (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    uuid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;