CREATE TABLE IF NOT EXISTS auth (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_uuid VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;